site_name: Workflow Orchestrator Programme
site_url: https://workfloworchestrator.org
nav:
  - Home: index.md
  - The programme:
    - About: about.md
    - Contact: contact.md
    - Leadership: leadership.md
  - Community:
    - Members: members.md
    - Media: meetings.md
  - Projects:
    - Orchestrator Core: '!include ./orchestrator-core/mkdocs.yml'
      # INCLUDED_REPO: https://github.com/workfloworchestrator/orchestrator-core.git
    - Orchestrator UI Library: '!include ./orchestrator-ui-library/mkdocs/mkdocs.yml'
      # INCLUDED_REPO: https://github.com/workfloworchestrator/orchestrator-ui-library.git

theme:
  name: material
  favicon: "img/favicon.ico"
  logo: img/WFO-Emblem-White.png
  palette:
  - scheme: default
    primary: teal
    accent: amber
    toggle:
      icon: material/lightbulb-outline
      name: Switch to light mode
  - scheme: slate
    primary: teal
    accent: amber
    toggle:
      icon: material/lightbulb
      name: Switch to dark mode
  features:
    - navigation.sections
    #- navigation.tabs
    # - navigation.tabs.sticky
  icon:
    repo: fontawesome/brands/github-alt
extra_css:
  - css/style.css
repo_name: workfloworchestrator
repo_url: https://github.com/workfloworchestrator
copyright: Copyright &copy; 2018 - 2024 Workflow Orchestrator Programme
extra:
  generator: false
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/fQkQn5ajFR
      name: WFO on Discord!
plugins:
  - search
  - privacy
  - social
  - monorepo
